### ISSUE TITLE
نشون دادن تاریخچه خریدها به شکل جدول

### ISSUE THREAD

**Issue by jadijadi** [jadijadi/digikala_history#2]
بعد از پایان اجرا، خروجی ها به شکل متن خالص نشون داده می شن. خوبه اونجا یک جدول باشه که خروجی رو مرتب ببینیم

**Comment by farshadseifi** [comment]
جادی به پول ریکوئست نگاه کن من درستش کردم
زیاد هم راحت نبودا 😉
