### ISSUE TITLE
توضیحات شروع برنامه

### ISSUE THREAD

**Issue by jadijadi** [jadijadi/digikala_history#21]
بهتره موقع شروع برنامه در یکی از باکس ها، اطلاعات مربوط به برنامه باشه و اینکه چیه و چیکار می کنه. که اگر به کسی رسید بفهمه با چی طرفه. در ساده ترین حالت می شه در لاگ دو سه خطی نوشت. اگر کسی خواست بتویسه حتما در مورد متنش با خودم مشورت کنه همینجا

**Comment by amirhnir** [comment]
من یه باکس زیر دکمه «اجرا» ایجاد کردم ، برای توضیحات هم متن زیر فکر میکنم خوب باشه (برگرفته از توضیحات ریلیز v0.1)

با اجرای برنامه و وارد کردن نام کاربری (ایمیل) و کلمه عبور، برنامه تاریخچه فعالیت شما رو از سایت دیجی کالا دریافت میکنه و نمایش میده. 
اطلاعات شما با هیچ جای دیگری به اشتراک گذاشته نمیشه و هیچ اطلاعات یا کلمه عبوری از شما نگهداری نمیشه :)

**Comment by amirhnir** [comment]
> فقط اگر این کار رو میکنی سعی کن فایل کیوتی رو هم ادیت کنی، چون من میخوام سعی کنم یوآی رو از فایل اصلی جدا کنم

منظورت از فایل کیوتی، اون فایل با پسوند **یو آی** هستش ؟

**Comment by farshadseifi** [comment]
دقیقا همون فایل یو آی. اون فایل رو همونطور که جادی نشون داد به راحتی میشه با کیوتی دیزاین ادیت کرد. من برای راحتی کار اول اونجا ادیت میکنم و بعد توی یه فایل دیگه اکسپورت میگیرم، بعد به خاطر اینکه پول ریکوئست دادنی مشکلی پیش نیاد با فایل اصلی مقایسه میکنم و تفاوتش رو دستی اضافه میکنم. اگر بتونم یوآی رو از فایل اصلی جدا کنم پروسه ی ادیت کردن یو آی راحت تر میشه

**Comment by amirhnir** [comment]
> دقیقا همون فایل یو آی. اون فایل رو همونطور که جادی نشون داد به راحتی میشه با کیوتی دیزاین ادیت کرد. من برای راحتی کار اول اونجا ادیت میکنم و بعد توی یه فایل دیگه اکسپورت میگیرم، بعد به خاطر اینکه پول ریکوئست دادنی مشکلی پیش نیاد با فایل اصلی مقایسه میکنم و تفاوتش رو دستی اضافه میکنم. اگر بتونم یوآی رو از فایل اصلی جدا کنم پروسه ی ادیت کردن یو آی راحت تر میشه

اوکی ! البته من با ادیت دستی راحتترم :)

**Comment by amirhnir** [comment]
> من یه باکس زیر دکمه «اجرا» ایجاد کردم ، برای توضیحات هم متن زیر فکر میکنم خوب باشه (برگرفته از توضیحات ریلیز v0.1)
> 
> با اجرای برنامه و وارد کردن نام کاربری (ایمیل) و کلمه عبور، برنامه تاریخچه فعالیت شما رو از سایت دیجی کالا دریافت میکنه و نمایش میده.
> اطلاعات شما با هیچ جای دیگری به اشتراک گذاشته نمیشه و هیچ اطلاعات یا کلمه عبوری از شما نگهداری نمیشه :)

جادی ؟! نظرتو درباره متن نگفتی ؟!؟

**Comment by jadijadi** [comment]
گفتم دیگه. یه دونه thumbs up گذاشتم یعنی خوبه (ک
