### ISSUE TITLE
کرش کردن برنامه وقتی به سفارش های کنسل شده میرسیم

### ISSUE THREAD

**Issue by smzerehpoush** [jadijadi/digikala_history#36]
وقتی برنامه رو بصورت عادی اجرا میکنم.لاگین موفق شده و چند تا از صفحه هارو پارس میکنه ولی بعدش این ارور رو میده.

> Traceback (most recent call last):
  File "digikala_history/digikala_history.py", line 103, in run
    extract_data(one_page, all_orders, all_post_prices)
  File "digikala_history/digikala_history.py", line 69, in extract_data
    dkpost_price = soup.find_all('div', class_='c-table-draught__col')[3].get_text()
IndexError: list index out of range

**Comment by saeedmhq** [comment]
> وقتی برنامه رو بصورت عادی اجرا میکنم.لاگین موفق شده و چند تا از صفحه هارو پارس میکنه ولی بعدش این ارور رو میده.
> 
> > Traceback (most recent call last):
> > File "digikala_history/digikala_history.py", line 103, in run
> > extract_data(one_page, all_orders, all_post_prices)
> > File "digikala_history/digikala_history.py", line 69, in extract_data
> > dkpost_price = soup.find_all('div', class_='c-table-draught__col')[3].get_text()
> > IndexError: list index out of range

وقتی به یه سفارش لغو شده میرسه این اتفاق میفته
میتونید با یه ترای/اکسپت ساده مواردی که کرش میکنه رو چک کنید
مثلا
`            try:
                dkpost_price = soup.find_all('div', class_='c-table-draught__col')[3].get_text()
                post_price = dkprice_to_numbers(dkpost_price)
                all_post_prices.append(post_price)
            except:
                print("tried but failed") `

**Comment by smzerehpoush** [comment]
راه حل شما رو تست کردم ولی این شکلی میشه

> 14107 segmentation fault  python3 w/digikala_history/digikala_history.py
یک نکته دیگه اینکه قبلا کار میکرد این الان نمیدونم چیشده که کار نمی کنه
