### ISSUE TITLE
آیکون برنامه

### ISSUE THREAD

**Issue by jadijadi** [jadijadi/digikala_history#4]
برنامه آیکون نداره. یه آیکون آزاد می تونه خوب باشه

**Comment by ssmns** [comment]
برطرف شد

**Comment by jadijadi** [comment]
کجا؟ باید پول ریکوئست بدی و بگی بر اساس فلان پول ریکوئست این حل شده. البته در چنین موردی بهتره توی همین گپ بگی که فلان آیکون به نظرتون چطوره و ... (:‌

**Comment by jadijadi** [comment]
دقت کنید که نباید از لوگوی دیجیکالا استفاده کنیم. باید چیزی شبیه هیستوری یا تحلیل یا اینها باشه و آزاد

**Comment by farshadseifi** [comment]
جادی نظرت در مورد این لوگو چیه؟
![timeline](https://user-images.githubusercontent.com/21032757/51822892-e7ecda00-22f2-11e9-8453-38553b167752.png)

<div>Icons made by <a href="https://www.freepik.com/" title="Freepik">Freepik</a> from <a href="https://www.flaticon.com/" 			    title="Flaticon">www.flaticon.com</a> is licensed by <a href="http://creativecommons.org/licenses/by/3.0/" 			    title="Creative Commons BY 3.0" target="_blank">CC 3.0 BY</a></div>

**Comment by jadijadi** [comment]
اگر آزاده، خیلی هم خوبه

sent from a mobile phone

**Comment by farshadseifi** [comment]
با توجه به لایسنسش رایگانه
`Free License (with attribution)
[](https://file000.flaticon.com/downloads/license/license.pdf)

**Comment by farshadseifi** [comment]
پول ریکوئستش رو فرستادم
کد سه خط تغییر داشته، که دو خط مربوط به لوگو هست و یک خط هم مربوط به تغییر نام لوگوی قبلی
لوگوی قبلی رو حذف کردم و دو فایل جدید (یکی لوگو و یکی هم آیکون) فرستادم
